language: rust

addons:
  apt:
    sources:
      - perl

rust: beta

before_install:
  - curl -L https://cpanmin.us | perl - -n App::cpanminus local::lib FFI::Platypus File::Which Test::Script IPC::Run3 File::chdir

install:
  - perl -V

script:
  - perl Build.PL
  - ./Build --verbose
  - ./Build test --verbose

env:
  - PERL5LIB=$HOME/perl5/lib/perl5 FFI_PLATYPUS=1
  - PERL5LIB=$HOME/perl5/lib/perl5 FFI_PLATYPUS_DEBUG_FAKE32=1
  - PERL5LIB=$HOME/perl5/lib/perl5 FFI_PLATYPUS_NO_ALLOCA=1
  - PERL5LIB=$HOME/perl5/lib/perl5 FFI_PLATYPUS_DEBUG_FAKE32=1 FFI_PLATYPUS_NO_ALLOCA=1
