language: rust

addons:
  apt:
    sources:
      - perl

rust: stable

before_install:
  - curl -L https://cpanmin.us | perl - --installdeps .

install:
  - perl -V

script:
  - perl Makefile.PL
  - make
  - make test TEST_VERBOSE=1

env:
  - PERL5LIB=$HOME/perl5/lib/perl5 FFI_PLATYPUS=1
  - PERL5LIB=$HOME/perl5/lib/perl5 FFI_PLATYPUS_DEBUG_FAKE32=1
  - PERL5LIB=$HOME/perl5/lib/perl5 FFI_PLATYPUS_NO_ALLOCA=1
  - PERL5LIB=$HOME/perl5/lib/perl5 FFI_PLATYPUS_DEBUG_FAKE32=1 FFI_PLATYPUS_NO_ALLOCA=1
