language: rust

before_install:
  - sudo apt-get install perl
  - sudo apt-get install cpanminus
  - sudo cpanm -n FFI::Platypus
  - sudo cpanm -n File::Which

install:
  - perl -V

script:
  - perl Build.PL
  - ./Build --verbose
  - ./Build test --verbose
  - ./Build install --verbose

env:
  - FFI_PLATYPUS=1
#  - FFI_PLATYPUS_DEBUG_FAKE32=1
#  - FFI_PLATYPUS_NO_ALLOCA=1
  - FFI_PLATYPUS_DEBUG_FAKE32=1 FFI_PLATYPUS_NO_ALLOCA=1
