language: rust

before_install:
  - sudo apt-get install perl
  - sudo apt-get install cpanminus
  - sudo cpanm -n FFI::Platypus

install:
  - true

perl:
#  - "5.8"
#  - "5.10"
#  - "5.12"
#  - "5.14"
#  - "5.16"
  - "5.18"
  - "5.20"

script:
  - perl Build.PL
  - ./Build --verbose
  - ./Build test --verbose
  - ./Build install --verbose

