---
abstract: 'Tools and documentation for using Platypus with the Rust programming language'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-Platypus-Lang-Rust
provides:
  FFI::Platypus::Lang::Rust:
    file: lib/FFI/Platypus/Lang/Rust.pm
    version: '0.01'
requires:
  FFI::Platypus: '0.16'
  perl: '5.008001'
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
